[build]
  command = """
    pip install -r requirements.txt && \
    cp jerseys.json netlify/functions/api/ && \
    cp jerseys.json netlify/functions/proxy-image/ && \
    cd netlify/functions/api && pip install -r requirements.txt && cd ../../.. && \
    cd netlify/functions/proxy-image && pip install -r requirements.txt && cd ../../..
  """
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/proxy/image/*"
  to = "/.netlify/functions/proxy-image/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  PYTHON_VERSION = "3.8"

[functions.api]
  runtime = "python3.8"

[functions."proxy-image"]
  runtime = "python3.8" 