[build]
  command = """
    pip install -r requirements.txt && \
    pip install -r netlify/functions/api/requirements.txt && \
    pip install -r netlify/functions/proxy-image/requirements.txt
  """
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/proxy/image/*"
  to = "/.netlify/functions/proxy-image/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  included_files = [
    "netlify/functions/shared/**/*",
    "netlify/functions/api/**/*",
    "netlify/functions/proxy-image/**/*"
  ]

[build.environment]
  PYTHON_VERSION = "3.8"

[functions.api]
  runtime = "python3.8"
  included_files = [
    "netlify/functions/api/**/*",
    "netlify/functions/shared/**/*"
  ]

[functions."proxy-image"]
  runtime = "python3.8"
  included_files = [
    "netlify/functions/proxy-image/**/*",
    "netlify/functions/shared/**/*"
  ]

