[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["flask", "werkzeug", "requests", "beautifulsoup4", "urllib3"] 