[build]
  command = """
    pip install -r requirements.txt && \
    cd functions && pip install -r requirements.txt && \
    cp ../jerseys.json . && \
    cd ..
  """
  publish = "."
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/proxy/image/*"
  to = "/.netlify/functions/proxy-image/:splat"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[build.environment]
  PYTHON_VERSION = "3.8"

[functions."api"]
  runtime = "python"

[functions."proxy-image"]
  runtime = "python" 