[build]
  command = "pip install -r requirements.txt"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild" 